### ISSUE TITLE
Building via SwiftPM for Catalyst using Xcode 11.4 beta fails 

### ISSUE THREAD

**Issue by rhettdickson** [algolia/instantsearch-core-swift#103]
**Describe the bug 🐛**
Attempting to build an Xcode project with instantsearch-core-swift added as a Swift package using Xcode 11.4 beta for Catalyst fails due to usage of CoreTelephony symbols

**To Reproduce 🔍**
1. Install latest Xcode 11.4 beta
2. Create a new iOS Xcode project, enable Catalyst (click Mac checkbox in target's General settings)
3. Add instantsearch-core-swift to packages via swiftpm
4. Build for macOS target

**Expected behavior 💭**
Build succeeds

**Actual behavior**

Build fails with:
.../SourcePackages/checkouts/algoliasearch-client-swift/Sources/AlgoliaSearch-Client/Network.swift:95:31: Use of unresolved identifier 'CTTelephonyNetworkInfo'

**Screenshots 🖥**
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/720958/76109983-71f58080-5f92-11ea-8374-0c29bc29113b.png">

**Environment:**
 - OS: macOS Catalina
 - Xcode: 11.4 Beta

**Comment by VladislavFitz** [comment]
Hi @rhettdickson 
Thank you for reporting this. 
The patch 7.0.4 of InstantSearch Client (a dependency of InstantSearch Core) which has just been released fixes this failure.
Update your SPM dependencies to have the issue resolved.
