### ISSUE TITLE
canLoadMore() not working

### ISSUE THREAD

**Issue by FrancoisObob** [algolia/instantsearch-core-swift#25]
Hi,

we just encountered a bug on one of our product list, the pagination is not working. 
In Searcher.swift, the `canLoadMore` function return false in this particular case. 

![capture d ecran 2018-06-04 a 18 09 27](https://user-images.githubusercontent.com/5428399/40928948-5c204c80-6823-11e8-8053-51965a6a81bc.png)

As you can see on the screenshot, the `isEqual` function return false, specifically when comparing the numeric filters. In this case they are the same, just not in the same order. 

The solution will be to sort both `numericRefinements.keys` or remove the cast in Array.

Have a nice day,

**Comment by spinach** [comment]
Thanks for reporting this @FrancoisObob! This is fixed in #26 and is being deployed right now with v3.2.5.
