### ISSUE TITLE
last version available : 3.2.1

### ISSUE THREAD

**Issue by FrancoisObob** [algolia/instantsearch-core-swift#28]
Hey, 
we wanted to try the last version embedding the fix for infinite lists, but it looks like versions 3.2.2 to 3.2.5 are not available via cocoapods. (version 3.2.1 is from Dec 2017)
Could you fix this please ? 😇
Have a nice day !

**Comment by robertmogos** [comment]
Hi @FrancoisObob. If you check https://cocoapods.org/pods/InstantSearchCore it seems that 3.2.5 is the latest version. Did you do `pod update` before `pod install` ?

**Comment by learnbit** [comment]
it stills gets the 3.2.1 version even doing pod update before pod install

**Comment by spinach** [comment]
Hey @francoischalifour 

If you're not using this already: can you try this in your podfile:

```
pod 'InstantSearchCore', '~> 3.2'
```

**Comment by learnbit** [comment]
<img width="1192" alt="screen shot 2018-11-21 at 09 42 17" src="https://user-images.githubusercontent.com/37585248/48844994-c2cb7080-ed71-11e8-9a8d-5e5286b6cc76.png">
still suggesting old version on the docs

**Comment by spinach** [comment]
Hey @learnbit,

You are right, the community website is outdated, and is actually being deprecated. Soon, all of this will move to the official www.algolia.com/doc site (being tested now). 

For now, I added an installation guide in the README [here](https://github.com/algolia/instantsearch-core-swift#installation). Thanks a lot for your feedback!
